### ISSUE TITLE
interpolation in tensorflow

### ISSUE THREAD

**Issue by mirca** [mirca/vaneska#1]
I couldn't find a bivariate interpolation routine in tensorflow like `scipy.interpolate.RectBivariateSpline`, so that we can parametrize data-driven models.

**Comment by benmontet** [comment]
Check out the p_operator piece of code in my nutella repository for some code that does this!

**Comment by benmontet** [comment]
Specifically [18] here: https://github.com/benmontet/nutella/blob/master/tensorflow_usable_psf_example.ipynb
