### ISSUE TITLE
Interpolation into the Kepler pixels should be an integration

### ISSUE THREAD

**Issue by benmontet** [mirca/vaneska#3]
The call to "evaluate" right now inside of __call__ returns an interpolation of the PRF model onto the Kepler grid. But this is just going to take the value at a discrete point. The PRF is small and quickly changing relative to the size of a Kepler pixel. What we really want is the PRF integrated over that pixel, which is going to be substantially different in some cases!

**Comment by mirca** [comment]
I agree! That shouldn't be difficult https://docs.scipy.org/doc/scipy/reference/generated/scipy.interpolate.RectBivariateSpline.integral.html#scipy.interpolate.RectBivariateSpline.integral

**Comment by benmontet** [comment]
Great. Although I worry about speed, since it seems like this would be a separate call to .integral for each call.

I bet we will do faster by writing our own leveraging some of the symmetry of our problem. We should know that, for a shift of some fraction of a sub-pixel element, any sub-pixel element gets flux from four neighboring pixels, with weights corresponding to the size of the shift, so we should be able to do the weighted sum of four shifts (where we shift by (x,y), (x+1, y), (x, y+1), and (x+1, y+1) sub-pixel elements and then collapse that down onto the Kepler pixel grid with a clever reshape and sum. This is the logic behind my old p_operator code in nutella and I think this is going to end up being faster than doing numerical integration on a spline.

**Comment by benmontet** [comment]
Actually what we want is scipy.ndimage.interpolation.shift. We can change the evaluate call so that:

-We can convert xc and yc into subpixels by multiplying by self.ss
-Then use interpolation shift (order 1, mode='constant', cval=0.0) to shift the PRF into where we want it
-Then integrate by using reshape to shape ((nrows, self.ss, ncols, self.ss)) and summing over axis 1 and 3.

And that (including multiplying by the flux) should get us exactly what we want!

We will need a derivative of interpolation shift, right? I think that's the trickiest part here.

Then we'll never use that second interpolation, so we can get rid of it. Can I task you with creating that derivative and I'll take care of the rest?

**Comment by mirca** [comment]
Oh yeah! Let's do that!

**Comment by mirca** [comment]
@benmontet, I've moved your commits to the ``develop`` branch, let's try these ideas there!

**Comment by dfm** [comment]
Dudes. You only want the integral if the PSF is actually the PSF and not the *pixel-convolved PSF*, but the only thing that you can ever measure is the pixel-convolved PSF so you don't want to do the integral.

**Comment by mirca** [comment]
@dfm That's true

**Comment by benmontet** [comment]
Am I correct that if we did this we would need to assume every pixel is
identical? Fitting multiple stars simultaneously, each part of the
pixel-convolved PRF would be convolved with a different part of a different
pixel and I don’t see how the math would work out there? Or am I thinking
about this the wrong way?

**Comment by dfm** [comment]
It's true that if you think that you'll be able to resolve differences in the shape of the sub-pixel flat between pixels then you're right - you'll need to do an integral inside of your code - but you won't be able to use the Kepler PRF for that. If you're willing to assume that each pixel has the same sub-pixel flat, it doesn't matter where on the pixel the center of the stars are - that's the whole point!

**Comment by benmontet** [comment]
Okay, I think I'm on the same page. Just to make sure:

Effectively, the PRF we learn (once we're learning it, rather than just applying one) would be a lookup table of, at each point, what the integrated flux for the pixel around it would be if that point were at the center of the pixel. In a case where the actual intra-pixel flat field was changing quickly relative to the instrumental PSF, we'd actually see those variations inside of the learned PRF (which we'll learn on some super-sampled grid, which we've interpolated the very fine Bryson+ PRF onto as an initial guess---and right now are treating as perfect).

Is that a correct way to think about it?

**Comment by dfm** [comment]
That sounds exactly right!
